### ISSUE TITLE
[OGLE17aaj] Redshift in ATEL 9977 

### ISSUE THREAD

**Issue by kponder** [astrocatalogs/tidaldisruptions#2]
OGLE17aaj: The ATEL 9977 gives this object's redshift as 0.116, but this object shows up as having no redshift. 

Thanks!

**Comment by guillochon** [comment]
Thanks @kponder, redshift added in https://github.com/astrocatalogs/tde-internal/commit/42660aed319c0e5a74e6d8e70186a0c1d3717b82. Will be live on tde.space in ~hour.

**Comment by kponder** [comment]
Thanks!
