### ISSUE TITLE
[PS1-10jh] difference with publish data

### ISSUE THREAD

**Issue by sjoertvv** [astrocatalogs/tidaldisruptions#4]
The source of the optical data for this source is given as 012Natur.485..217G. But when I check the data published with this paper, the values listed there are brighter by about 0.1 mag. 

For example, for 55350.5 MJD, the r-band mag in the Open catalog is 21.92, while the published value is 21.80. 

Could difference be due to a correction for Galactic extinction (ie, the Open catalog values are _not_ corrected). The value `mcorrected` is not given in the JSON, so I don't know if I should apply an extinction correction or not.  

Quite a few other sources in the Open catalog don't have the key `mcorrected`. I suppose that when is key is missing, the data could either be correct or not corrected?

**Comment by guillochon** [comment]
`mcorrected` is omitted when we are not sure if it has been applied or not.

As for the difference between the posted data and the 2012 paper, I *think* the data on the page might be from the 2015 Gezari paper instead, if that's the case then it should be tagged with both sources but it currently is not. Could you check and see if that's possibly correct? It's also possibly the `mcorrected` issue you mentioned.

**Comment by sjoertvv** [comment]
The 2015 paper does mention a re-analysis of the PS1 data, but the data is not published (I checked the journal website). So perhaps this was sent to you directly?

**Comment by guillochon** [comment]
You are correct @sjoertvv, I received the photometry via an e-mail from Suvi in 2016, and somehow did not update the reference on the page to reflect that the source is the 2015 paper now. I've gone ahead and pushed some updates that credit both papers for this photometry (https://github.com/astrocatalogs/tde-external/commit/4c907eda9e274d7089b058accb0f03c9f267f9ad and https://github.com/astrocatalogs/tidaldisruptions/commit/f82b5f17daa490894b29a5d2089ff78d3fe54862), and have triggered a rebuild of the catalog, the updated source attribution should appear in ~1 hour.

Unfortunately, Suvi did not tell me if galactic extinction was applied or not to the table she sent me, I suspect it wasn't and the change in values simply come from the re-analysis of the photometry. Probably best to ask Suvi directly (she doesn't appear to mention this in the paper either).

**Comment by guillochon** [comment]
Properly labeled now on the page, thanks for bringing this to my attention!
